#Name of the workflow
name: CI

#Trigger on "PUSH" or "PR" request to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  #First job test: Run on separate runner
  test:
    name: Run tests
    #This job will run on ubuntu machine
    runs-on: ubuntu-latest

    #env block at the job level make these variable available to every step in the job!
    env:
      #"secrets" object contains all the secrets that we have defined in the repository settings. We can access them via the syntax below. secrets.SECRET_VAR inside double curly brances, prefixed by the dollar sign $.

      APP_NAME: ${{secrets.APP_NAME}}
      NODE_ENV: ${{secrets.NODE_ENV}}

    steps:
      #Every step carries a human friendly name, and either an action or a command to run via "uses" and "run" respectively

      #First step is always to checkout code via actions/checkout action. This will clone the repo in the runner
      - name: Checkout code
        uses: actions/checkout@v4

      #After code is setup, we install everything that's needed to run the application. First install the NPM itself
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      #Then install the dependencies via npm ci command, which is faster and more reliable than npm install for CI environments
      - name: Install dependencies
        run: npm ci

      #At the end we run the tests
      - name: Run tests
        run: npm test

    #Second job: Deploy
  deploy:
    name: Deploy to Render
    needs: test #This job will only run if the "test" job is successful
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #This job will only run if the event is a push(second condition) to the main branch(first condition). It only works on actualy pushes to main, not on PRs, which is what we want for deployment

    steps:
      - name: Trigger deployment
        run: |
          curl -s "${{ secrets.RENDER_DEPLOY_HOOK }}" \
            -X POST \
            -o /dev/null \
            -w "Deploy triggered: HTTP %{http_code}\n"
            
          #The curl command sends a POST request to the Render deploy hook URL, which is stored as a secret in the repository settings. The -s flag makes curl silent, -X POST specifies the request method, -o /dev/null discards the response body, and -w "Deploy triggered: HTTP %{http_code}\n" prints the HTTP status code of the response for logging purposes.
